/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.demo.animalshelter;

import com.demo.animalshelter.dto.AdopterDTO;
import com.demo.animalshelter.service.AdopterService;
import com.demo.animalshelter.service.AdopterServiceImpl;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    
    //private AdopterService adopterService = new AdopterServiceImpl();

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        AdopterService adopterService = new AdopterServiceImpl();
        
        
        System.out.println("Scenario 1: Insert a single record");
        System.out.print("Trying to insert a record: ");
        AdopterDTO adopterDTO = new AdopterDTO();
        adopterDTO.setAdopterEmail("someemail");
        adopterDTO.setAdopterName("someName");
        adopterDTO.setPhoneNumber("1234512345");
        System.out.println(adopterDTO);
        adopterService.addAdopter(adopterDTO);
        
        System.out.println("Scenario 2: Delete a single record");
        adopterService.delete("mad@gmail.com");
    }
}
